//
// Created by ChrisRodinbell on 2020/5/19.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnigpio_GPIOControl */

#ifndef _Included_jnigpio_GPIOControl
#define _Included_jnigpio_GPIOControl
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_zhuang_jnigpio_GPIOControl
* Method:    exportGpio
* Signature: (I)I
*/
JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_exportGpio(JNIEnv *env, jclass clazz, jint gpio);

/*
 * Class:     com_zhuang_jnigpio_GPIOControl
 * Method:    setGpioDirection
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_setGpioDirection(JNIEnv *env, jclass clazz, jint gpio,
                                          jint direction);

/*
 * Class:     com_zhuang_jnigpio_GPIOControl
 * Method:    readGpioStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_readGpioStatus(JNIEnv *env, jclass clazz, jint gpio);

/*
 * Class:     com_zhuang_jnigpio_GPIOControl
 * Method:    writeGpioStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_writeGpioStatus(JNIEnv *env, jclass clazz, jint gpio, jint value);

/*
 * Class:     com_zhuang_jnigpio_GPIOControl
 * Method:    unexportGpio
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_unexportGpio(JNIEnv *env, jclass clazz, jint gpio);

JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_getDeviceStatus(JNIEnv *env, jclass clazz, jstring device_path);

JNIEXPORT jint JNICALL
Java_jnigpio_GPIOControl_setDeviceStatus(JNIEnv *env, jclass clazz, jstring device_path, jint status);

//Utils
jstring charToJstring(JNIEnv *env, const char *pat);

char *stringToChar(JNIEnv *env, jstring jstr);

#ifdef __cplusplus
}
#endif
#endif