//
// Created by ChrisRodinbell on 2020/5/19.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnigpio_GPIOControl */

#ifndef _Included_jnisctool_SCTool
#define _Included_jnigpio_GPIOControl
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_jnisctool_SCTool_nativeDecrypt(JNIEnv *env, jclass clazz, jint type, jbyteArray src,
                                    jbyteArray dec);
JNIEXPORT void JNICALL
Java_jnisctool_SCTool_nativeClose(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif